/*
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.OntologyRefernce;
import io.swagger.client.model.TraitDataType;
import io.swagger.client.model.ValidValues;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * New scale request object
 */
@Schema(description = "New scale request object")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-15T17:05:32.234Z[GMT]")public class NewScaleRequest {

  @SerializedName("dataType")
  private TraitDataType dataType = null;

  @SerializedName("decimalPlaces")
  private Integer decimalPlaces = null;

  @SerializedName("ontologyRefernce")
  private OntologyRefernce ontologyRefernce = null;

  @SerializedName("scaleName")
  private String scaleName = null;

  @SerializedName("validValues")
  private ValidValues validValues = null;

  @SerializedName("xref")
  private String xref = null;
  public NewScaleRequest dataType(TraitDataType dataType) {
    this.dataType = dataType;
    return this;
  }

  

  /**
  * Get dataType
  * @return dataType
  **/
  @Schema(description = "")
  public TraitDataType getDataType() {
    return dataType;
  }
  public void setDataType(TraitDataType dataType) {
    this.dataType = dataType;
  }
  public NewScaleRequest decimalPlaces(Integer decimalPlaces) {
    this.decimalPlaces = decimalPlaces;
    return this;
  }

  

  /**
  * For numerical, number of decimal places to be reported
  * @return decimalPlaces
  **/
  @Schema(description = "For numerical, number of decimal places to be reported")
  public Integer getDecimalPlaces() {
    return decimalPlaces;
  }
  public void setDecimalPlaces(Integer decimalPlaces) {
    this.decimalPlaces = decimalPlaces;
  }
  public NewScaleRequest ontologyRefernce(OntologyRefernce ontologyRefernce) {
    this.ontologyRefernce = ontologyRefernce;
    return this;
  }

  

  /**
  * Get ontologyRefernce
  * @return ontologyRefernce
  **/
  @Schema(description = "")
  public OntologyRefernce getOntologyRefernce() {
    return ontologyRefernce;
  }
  public void setOntologyRefernce(OntologyRefernce ontologyRefernce) {
    this.ontologyRefernce = ontologyRefernce;
  }
  public NewScaleRequest scaleName(String scaleName) {
    this.scaleName = scaleName;
    return this;
  }

  

  /**
  * Name of the scale
  * @return scaleName
  **/
  @Schema(description = "Name of the scale")
  public String getScaleName() {
    return scaleName;
  }
  public void setScaleName(String scaleName) {
    this.scaleName = scaleName;
  }
  public NewScaleRequest validValues(ValidValues validValues) {
    this.validValues = validValues;
    return this;
  }

  

  /**
  * Get validValues
  * @return validValues
  **/
  @Schema(description = "")
  public ValidValues getValidValues() {
    return validValues;
  }
  public void setValidValues(ValidValues validValues) {
    this.validValues = validValues;
  }
  public NewScaleRequest xref(String xref) {
    this.xref = xref;
    return this;
  }

  

  /**
  * Cross reference to the scale, for example to a unit ontology such as UO or to a unit of an external major database
  * @return xref
  **/
  @Schema(description = "Cross reference to the scale, for example to a unit ontology such as UO or to a unit of an external major database")
  public String getXref() {
    return xref;
  }
  public void setXref(String xref) {
    this.xref = xref;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewScaleRequest newScaleRequest = (NewScaleRequest) o;
    return Objects.equals(this.dataType, newScaleRequest.dataType) &&
        Objects.equals(this.decimalPlaces, newScaleRequest.decimalPlaces) &&
        Objects.equals(this.ontologyRefernce, newScaleRequest.ontologyRefernce) &&
        Objects.equals(this.scaleName, newScaleRequest.scaleName) &&
        Objects.equals(this.validValues, newScaleRequest.validValues) &&
        Objects.equals(this.xref, newScaleRequest.xref);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(dataType, decimalPlaces, ontologyRefernce, scaleName, validValues, xref);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewScaleRequest {\n");
    
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("    decimalPlaces: ").append(toIndentedString(decimalPlaces)).append("\n");
    sb.append("    ontologyRefernce: ").append(toIndentedString(ontologyRefernce)).append("\n");
    sb.append("    scaleName: ").append(toIndentedString(scaleName)).append("\n");
    sb.append("    validValues: ").append(toIndentedString(validValues)).append("\n");
    sb.append("    xref: ").append(toIndentedString(xref)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
