/*
 * BrAPI
 * The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.  <strong>General Reference Documentation</strong>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md\">URL Structure</a>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md\">Response Structure</a>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md\">Date/Time Encoding</a>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md\">Location Encoding</a>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md\">Error Handling</a>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md\">Search Services</a>  <a href=\"https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md\">Asynchronous Processing</a>
 *
 * OpenAPI spec version: 1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PhenotypesRequestObservation;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * new phenotypes
 */
@Schema(description = "new phenotypes")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-15T17:05:32.234Z[GMT]")public class PhenotypesRequestData {

  @SerializedName("observationUnitDbId")
  private String observationUnitDbId = null;

  @SerializedName("observations")
  private List<PhenotypesRequestObservation> observations = null;

  @SerializedName("studyDbId")
  private String studyDbId = null;
  public PhenotypesRequestData observationUnitDbId(String observationUnitDbId) {
    this.observationUnitDbId = observationUnitDbId;
    return this;
  }

  

  /**
  * Get observationUnitDbId
  * @return observationUnitDbId
  **/
  @Schema(description = "")
  public String getObservationUnitDbId() {
    return observationUnitDbId;
  }
  public void setObservationUnitDbId(String observationUnitDbId) {
    this.observationUnitDbId = observationUnitDbId;
  }
  public PhenotypesRequestData observations(List<PhenotypesRequestObservation> observations) {
    this.observations = observations;
    return this;
  }

  public PhenotypesRequestData addObservationsItem(PhenotypesRequestObservation observationsItem) {
    if (this.observations == null) {
      this.observations = new ArrayList<PhenotypesRequestObservation>();
    }
    this.observations.add(observationsItem);
    return this;
  }

  /**
  * Get observations
  * @return observations
  **/
  @Schema(description = "")
  public List<PhenotypesRequestObservation> getObservations() {
    return observations;
  }
  public void setObservations(List<PhenotypesRequestObservation> observations) {
    this.observations = observations;
  }
  public PhenotypesRequestData studyDbId(String studyDbId) {
    this.studyDbId = studyDbId;
    return this;
  }

  

  /**
  * Get studyDbId
  * @return studyDbId
  **/
  @Schema(description = "")
  public String getStudyDbId() {
    return studyDbId;
  }
  public void setStudyDbId(String studyDbId) {
    this.studyDbId = studyDbId;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhenotypesRequestData phenotypesRequestData = (PhenotypesRequestData) o;
    return Objects.equals(this.observationUnitDbId, phenotypesRequestData.observationUnitDbId) &&
        Objects.equals(this.observations, phenotypesRequestData.observations) &&
        Objects.equals(this.studyDbId, phenotypesRequestData.studyDbId);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(observationUnitDbId, observations, studyDbId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhenotypesRequestData {\n");
    
    sb.append("    observationUnitDbId: ").append(toIndentedString(observationUnitDbId)).append("\n");
    sb.append("    observations: ").append(toIndentedString(observations)).append("\n");
    sb.append("    studyDbId: ").append(toIndentedString(studyDbId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
